spring:
  application:
    name: spring-dynamodb-example

server:
  port: 8081

app:
  config:
    dynamodb:
      access-key: <YOUR_ACCESS_KEY>
      secret-key: <YOUR_SECRET_KEY>
      end-point-url: http://dynamodb.ap-south-1.amazonaws.com
      region: ap-south-1
